### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by ghost** [Sachin-v3rma/Astra#1]
is this my issue or the tools issue?full error below

Traceback (most recent call last):
  File "/root/Astra/Astra.py", line 172, in <module>
    asyncio.get_event_loop().run_until_complete(start(urls, threads))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/Astra/Astra.py", line 142, in start
    await asyncio.gather(*tasks)
  File "/root/Astra/Astra.py", line 123, in parser
    html = await fetch(session=session, url=url)
  File "/root/Astra/Astra.py", line 86, in fetch
    html = await response.text()
  File "/usr/lib/python3/dist-packages/aiohttp/client_reqrep.py", line 1081, in text
    return self._body.decode(encoding, errors=errors)  # type: ignore
  File "/usr/lib/python3.9/encodings/cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 183079: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Astra/Astra.py", line 188, in <module>
    print(f'\n{col.magenta}[-]{col.red} Error : {repr(err)}{col.reset}')
BrokenPipeError: [Errno 32] Broken pipe

**Comment by ghost** [comment]
if -ns is used i see that the borken pipe error does not happen.

**Comment by Sachin-v3rma** [comment]
Did one of your urls contain a image/gif or binary data or its throwing this error on all urls ? I think its due to binary/unicode data in response. Fix would be to just ignore those files. I have fixed it can u confirm ?
